# -*- coding: utf-8 -*-
"""WebScrapingusingPython.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AqV5DIi5I7REtbTrSgKYIG1fJ9Y3Hu7b
"""

!pip install selenium
!apt-get update 
!apt install chromium-chromedriver

from selenium import webdriver
options = webdriver.ChromeOptions()
options.add_argument('--headless')
options.add_argument('--no-sandbox')
options.add_argument('--disable-dev-shm-usage')
wd = webdriver.Chrome('chromedriver',options=options)
driver =webdriver.Chrome('chromedriver',options=options)

title=[] 
subtitle=[] 
driver.get("https://realpython.github.io/fake-jobs/jobs/senior-python-developer-0.html")

from bs4 import BeautifulSoup
import pandas as pd

content = driver.page_source
soup = BeautifulSoup(content)
for a in soup.findAll('div',href=True, attrs={'class':'box'}):
  title=a.find('h1', attrs={'class':'title is-2'})
  subtitle=a.find('h2', attrs={'class':'subtitle is-4 company'})
  title.append(title.text)
  subtitle.append(subtitle.text)

df = pd.DataFrame({'Employee Position':title,'Employee Name':subtitle}) 
df.to_csv('employee.csv', index=False, encoding='utf-8')